resources:
  - name: christianb
    type: GitRepo
    configuration:
      gitProvider: chb0github
      path: chb0github/jfrog-pipelines-health-check
pipelines:
  - name: christianb_pipeline_health_check
    steps:
      - name: health_check
        type: Bash
        configuration:
          priority: 0
          environmentVariables:
            ROUTING_KEY: '${int_PartnerEngineeringPagerDuty_NOTIFY_ROUTING_KEY}'
          integrations:
            - name: PagerDuty
            - name: PartnerEngineeringPagerDuty
          inputResources:
            - name: christianb
        execution:
          onExecute:
            - echo "Running $pipeline_name | $step_name with routing key '$ROUTING_KEY'"
            - send_notification PagerDuty --routingkey $ROUTING_KEY --text "hello world from bash run number $run_number"
