resources:
  - name: christianb
    type: GitRepo
    configuration:
      gitProvider: github
      path: chb0github/jfrog-pipelines-health-check
pipelines:
  - name: pipeline_health_check
    steps:
      - name: health_check
        type: Bash
        configuration:
          integrations:
            - name: PagerDutyRoutingKey
            - name: PartnerEngineeringPagerDuty
          inputResources:
            - name: christianb
        execution:
          onExecute:
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
            - send_notification PartnerEngineeringPagerDuty --routingkey $int_PagerDutyRoutingKey_NOTIFY_ROUTING_KEY --text "hello world from bash run number $run_number" 
