resources:
  - name: healthCheckRepo
    type: GitRepo
    configuration:
      gitProvider: JohnpGithub
      path: peters95/jfrog-pipelines-health-check
pipelines:
  - name: pipeline_health_check
    steps:
      - name: health_check
        type: Bash
        configuration:
          inputResources:
            - name: healthCheckRepo
        execution:
          onExecute:
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
